[package]
name = "rust-os"
version = "0.1.0"
authors = ["smazumder05 <smazumder@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.6.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
